/**
 * @author Aleksey Terzi
 */

package com.aleksey.castlegates.config;

import org.bukkit.Material;

public class ConfigDefaults {

    public static final String[] gearMaterials = new String[]{
        Material.STONE.name(),
        Material.GRASS_BLOCK.name(),
        Material.DIRT.name(),
        Material.COBBLESTONE.name(),

        Material.OAK_WOOD.name(),
        Material.OAK_LOG.name(),
        Material.OAK_PLANKS.name(),
        Material.OAK_STAIRS.name(),
        Material.OAK_FENCE.name(),
        Material.OAK_SLAB.name(),
        Material.STRIPPED_OAK_LOG.name(),
        Material.STRIPPED_OAK_WOOD.name(),

        Material.SPRUCE_WOOD.name(),
        Material.SPRUCE_LOG.name(),
        Material.SPRUCE_PLANKS.name(),
        Material.SPRUCE_STAIRS.name(),
        Material.SPRUCE_FENCE.name(),
        Material.SPRUCE_SLAB.name(),
        Material.STRIPPED_SPRUCE_LOG.name(),
        Material.STRIPPED_SPRUCE_WOOD.name(),

        Material.BIRCH_WOOD.name(),
        Material.BIRCH_LOG.name(),
        Material.BIRCH_PLANKS.name(),
        Material.BIRCH_STAIRS.name(),
        Material.BIRCH_FENCE.name(),
        Material.BIRCH_SLAB.name(),
        Material.STRIPPED_BIRCH_LOG.name(),
        Material.STRIPPED_BIRCH_WOOD.name(),

        Material.JUNGLE_WOOD.name(),
        Material.JUNGLE_LOG.name(),
        Material.JUNGLE_PLANKS.name(),
        Material.JUNGLE_STAIRS.name(),
        Material.JUNGLE_FENCE.name(),
        Material.JUNGLE_SLAB.name(),
        Material.STRIPPED_JUNGLE_LOG.name(),
        Material.STRIPPED_JUNGLE_WOOD.name(),

        Material.ACACIA_WOOD.name(),
        Material.ACACIA_LOG.name(),
        Material.ACACIA_PLANKS.name(),
        Material.ACACIA_STAIRS.name(),
        Material.ACACIA_FENCE.name(),
        Material.ACACIA_SLAB.name(),
        Material.STRIPPED_ACACIA_LOG.name(),
        Material.STRIPPED_ACACIA_WOOD.name(),

        Material.DARK_OAK_WOOD.name(),
        Material.DARK_OAK_LOG.name(),
        Material.DARK_OAK_PLANKS.name(),
        Material.DARK_OAK_STAIRS.name(),
        Material.DARK_OAK_FENCE.name(),
        Material.DARK_OAK_SLAB.name(),
        Material.STRIPPED_DARK_OAK_LOG.name(),
        Material.STRIPPED_DARK_OAK_WOOD.name(),

        Material.MANGROVE_WOOD.name(),
        Material.MANGROVE_LOG.name(),
        Material.MANGROVE_PLANKS.name(),
        Material.MANGROVE_STAIRS.name(),
        Material.MANGROVE_FENCE.name(),
        Material.MANGROVE_SLAB.name(),
        Material.STRIPPED_MANGROVE_LOG.name(),
        Material.STRIPPED_MANGROVE_WOOD.name(),

        Material.CHERRY_WOOD.name(),
        Material.CHERRY_LOG.name(),
        Material.CHERRY_PLANKS.name(),
        Material.CHERRY_STAIRS.name(),
        Material.CHERRY_FENCE.name(),
        Material.CHERRY_SLAB.name(),
        Material.STRIPPED_CHERRY_LOG.name(),
        Material.STRIPPED_CHERRY_WOOD.name(),

        Material.BAMBOO_BLOCK.name(),
        Material.BAMBOO_PLANKS.name(),
        Material.BAMBOO_STAIRS.name(),
        Material.BAMBOO_FENCE.name(),
        Material.BAMBOO_SLAB.name(),
        Material.STRIPPED_BAMBOO_BLOCK.name(),

        Material.CRIMSON_HYPHAE.name(),
        Material.CRIMSON_STEM.name(),
        Material.CRIMSON_PLANKS.name(),
        Material.CRIMSON_STAIRS.name(),
        Material.CRIMSON_FENCE.name(),
        Material.CRIMSON_SLAB.name(),
        Material.STRIPPED_CRIMSON_HYPHAE.name(),
        Material.STRIPPED_CRIMSON_STEM.name(),

        Material.WARPED_HYPHAE.name(),
        Material.WARPED_STEM.name(),
        Material.WARPED_PLANKS.name(),
        Material.WARPED_STAIRS.name(),
        Material.WARPED_FENCE.name(),
        Material.WARPED_SLAB.name(),
        Material.STRIPPED_WARPED_HYPHAE.name(),
        Material.STRIPPED_WARPED_STEM.name(),

        Material.PALE_OAK_WOOD.name(),
        Material.PALE_OAK_LOG.name(),
        Material.PALE_OAK_PLANKS.name(),
        Material.PALE_OAK_STAIRS.name(),
        Material.PALE_OAK_FENCE.name(),
        Material.PALE_OAK_SLAB.name(),
        Material.STRIPPED_PALE_OAK_LOG.name(),
        Material.STRIPPED_PALE_OAK_WOOD.name(),
        
        Material.GLASS.name(),
        Material.LAPIS_BLOCK.name(),
        Material.SANDSTONE.name(),

        Material.WHITE_WOOL.name(),
        Material.ORANGE_WOOL.name(),
        Material.MAGENTA_WOOL.name(),
        Material.LIGHT_BLUE_WOOL.name(),
        Material.YELLOW_WOOL.name(),
        Material.LIME_WOOL.name(),
        Material.PINK_WOOL.name(),
        Material.GRAY_WOOL.name(),
        Material.LIGHT_GRAY_WOOL.name(),
        Material.CYAN_WOOL.name(),
        Material.PURPLE_WOOL.name(),
        Material.BLUE_WOOL.name(),
        Material.BROWN_WOOL.name(),
        Material.GREEN_WOOL.name(),
        Material.RED_WOOL.name(),
        Material.BLACK_WOOL.name(),

        Material.GOLD_BLOCK.name(),
        Material.IRON_BLOCK.name(),
        Material.BRICK.name(),
        Material.MOSSY_COBBLESTONE.name(),
        Material.MOSSY_COBBLESTONE_SLAB.name(),
        Material.OBSIDIAN.name(),
        Material.DIAMOND_BLOCK.name(),
        Material.COBBLESTONE_STAIRS.name(),
        Material.COBBLESTONE_SLAB.name(),
        Material.ICE.name(),
        Material.SNOW_BLOCK.name(),
        Material.CLAY.name(),
        Material.NETHERRACK.name(),
        Material.GLOWSTONE.name(),
        Material.SMOOTH_STONE.name(),
        Material.IRON_BARS.name(),
        Material.BRICK_STAIRS.name(),
        Material.NETHER_BRICK.name(),
        Material.NETHER_BRICK_STAIRS.name(),
        Material.SANDSTONE_STAIRS.name(),
        Material.EMERALD_BLOCK.name(),
        Material.REDSTONE_BLOCK.name(),
        Material.QUARTZ_BLOCK.name(),
        Material.QUARTZ_STAIRS.name(),
        Material.ACACIA_STAIRS.name(),
        Material.DARK_OAK_STAIRS.name(),
        Material.HAY_BLOCK.name(),
        Material.COAL_BLOCK.name(),
        Material.PACKED_ICE.name(),
        Material.RED_SANDSTONE.name(),
        Material.RED_SANDSTONE_STAIRS.name(),
        Material.SPRUCE_FENCE.name(),
        Material.BIRCH_FENCE.name(),
        Material.JUNGLE_FENCE.name(),
        Material.DARK_OAK_FENCE.name(),
        Material.ACACIA_FENCE.name(),
        Material.PURPUR_BLOCK.name(),
        Material.PURPUR_STAIRS.name(),
        Material.PURPUR_SLAB.name(),
        Material.MAGMA_BLOCK.name(),
        Material.NETHER_WART_BLOCK.name(),
        Material.RED_NETHER_BRICKS.name(),
        Material.BONE_BLOCK.name()
    };

    public static final String[] bridgeMaterials = new String[]{
        Material.STONE.name(),
        Material.DIRT.name(),
        Material.COBBLESTONE.name(),

        Material.OAK_WOOD.name(),
        Material.OAK_LOG.name(),
        Material.OAK_PLANKS.name(),
        Material.OAK_FENCE.name(),
        Material.OAK_SHELF.name(),
        Material.STRIPPED_OAK_LOG.name(),
        Material.STRIPPED_OAK_WOOD.name(),

        Material.SPRUCE_WOOD.name(),
        Material.SPRUCE_LOG.name(),
        Material.SPRUCE_PLANKS.name(),
        Material.SPRUCE_FENCE.name(),
        Material.SPRUCE_SHELF.name(),
        Material.STRIPPED_SPRUCE_LOG.name(),
        Material.STRIPPED_SPRUCE_WOOD.name(),

        Material.BIRCH_WOOD.name(),
        Material.BIRCH_LOG.name(),
        Material.BIRCH_PLANKS.name(),
        Material.BIRCH_FENCE.name(),
        Material.BIRCH_SHELF.name(),
        Material.STRIPPED_BIRCH_LOG.name(),
        Material.STRIPPED_BIRCH_WOOD.name(),

        Material.JUNGLE_WOOD.name(),
        Material.JUNGLE_LOG.name(),
        Material.JUNGLE_PLANKS.name(),
        Material.JUNGLE_FENCE.name(),
        Material.JUNGLE_SHELF.name(),
        Material.STRIPPED_JUNGLE_LOG.name(),
        Material.STRIPPED_JUNGLE_WOOD.name(),

        Material.ACACIA_WOOD.name(),
        Material.ACACIA_LOG.name(),
        Material.ACACIA_PLANKS.name(),
        Material.ACACIA_FENCE.name(),
        Material.ACACIA_SHELF.name(),
        Material.STRIPPED_ACACIA_LOG.name(),
        Material.STRIPPED_ACACIA_WOOD.name(),

        Material.DARK_OAK_WOOD.name(),
        Material.DARK_OAK_LOG.name(),
        Material.DARK_OAK_PLANKS.name(),
        Material.DARK_OAK_FENCE.name(),
        Material.DARK_OAK_SHELF.name(),
        Material.STRIPPED_DARK_OAK_LOG.name(),
        Material.STRIPPED_DARK_OAK_WOOD.name(),

        Material.MANGROVE_WOOD.name(),
        Material.MANGROVE_LOG.name(),
        Material.MANGROVE_PLANKS.name(),
        Material.MANGROVE_FENCE.name(),
        Material.MANGROVE_SHELF.name(),
        Material.STRIPPED_MANGROVE_LOG.name(),
        Material.STRIPPED_MANGROVE_WOOD.name(),

        Material.CHERRY_WOOD.name(),
        Material.CHERRY_LOG.name(),
        Material.CHERRY_PLANKS.name(),
        Material.CHERRY_FENCE.name(),
        Material.CHERRY_SHELF.name(),
        Material.STRIPPED_CHERRY_LOG.name(),
        Material.STRIPPED_CHERRY_WOOD.name(),

        Material.PALE_OAK_WOOD.name(),
        Material.PALE_OAK_LOG.name(),
        Material.PALE_OAK_PLANKS.name(),
        Material.PALE_OAK_FENCE.name(),
        Material.PALE_OAK_SHELF.name(),
        Material.STRIPPED_PALE_OAK_LOG.name(),
        Material.STRIPPED_PALE_OAK_WOOD.name(),

        Material.CRIMSON_HYPHAE.name(),
        Material.CRIMSON_STEM.name(),
        Material.CRIMSON_PLANKS.name(),
        Material.CRIMSON_FENCE.name(),
        Material.CRIMSON_SHELF.name(),
        Material.STRIPPED_CRIMSON_HYPHAE.name(),
        Material.STRIPPED_CRIMSON_STEM.name(),

        Material.WARPED_HYPHAE.name(),
        Material.WARPED_STEM.name(),
        Material.WARPED_PLANKS.name(),
        Material.WARPED_FENCE.name(),
        Material.WARPED_SHELF.name(),
        Material.STRIPPED_WARPED_HYPHAE.name(),
        Material.STRIPPED_WARPED_STEM.name(),

        Material.BAMBOO_BLOCK.name(),
        Material.BAMBOO_PLANKS.name(),
        Material.BAMBOO_FENCE.name(),
        Material.BAMBOO_SHELF.name(),
        Material.STRIPPED_BAMBOO_BLOCK.name(),
        Material.BAMBOO_MOSAIC.name(),

        Material.GLASS.name(),
        Material.LAPIS_BLOCK.name(),
        Material.SANDSTONE.name(),

        Material.WHITE_WOOL.name(),
        Material.ORANGE_WOOL.name(),
        Material.MAGENTA_WOOL.name(),
        Material.LIGHT_BLUE_WOOL.name(),
        Material.YELLOW_WOOL.name(),
        Material.LIME_WOOL.name(),
        Material.PINK_WOOL.name(),
        Material.GRAY_WOOL.name(),
        Material.LIGHT_GRAY_WOOL.name(),
        Material.CYAN_WOOL.name(),
        Material.PURPLE_WOOL.name(),
        Material.BLUE_WOOL.name(),
        Material.BROWN_WOOL.name(),
        Material.GREEN_WOOL.name(),
        Material.RED_WOOL.name(),
        Material.BLACK_WOOL.name(),

        Material.GOLD_BLOCK.name(),
        Material.IRON_BLOCK.name(),
        Material.BRICK.name(),
        Material.MOSSY_COBBLESTONE.name(),
        Material.DIAMOND_BLOCK.name(),
        Material.COBBLESTONE_STAIRS.name(),
        Material.ICE.name(),
        Material.SNOW_BLOCK.name(),
        Material.CLAY.name(),
        Material.NETHERRACK.name(),
        Material.GLOWSTONE.name(),
        Material.BRICK_STAIRS.name(),
        Material.NETHER_BRICK.name(),
        Material.NETHER_BRICK_STAIRS.name(),
        Material.SANDSTONE_STAIRS.name(),
        Material.EMERALD_BLOCK.name(),
        Material.REDSTONE_BLOCK.name(),
        Material.QUARTZ_BLOCK.name(),
        Material.QUARTZ_STAIRS.name(),
        Material.ACACIA_STAIRS.name(),
        Material.DARK_OAK_STAIRS.name(),
        Material.HAY_BLOCK.name(),
        Material.COAL_BLOCK.name(),
        Material.PACKED_ICE.name(),
        Material.RED_SANDSTONE.name(),
        Material.RED_SANDSTONE_STAIRS.name(),
        Material.SPRUCE_FENCE.name(),
        Material.BIRCH_FENCE.name(),
        Material.JUNGLE_FENCE.name(),
        Material.DARK_OAK_FENCE.name(),
        Material.ACACIA_FENCE.name(),
        Material.PURPUR_BLOCK.name(),
        Material.PURPUR_STAIRS.name(),
        Material.PURPUR_SLAB.name(),
    };
}
