CREATE DATABASE donum;
CREATE DATABASE banstick;
CREATE DATABASE bastion;
CREATE DATABASE citadel;
CREATE DATABASE civchat2;
CREATE DATABASE civduties;
CREATE DATABASE jukealert;
CREATE DATABASE namelayer;
CREATE DATABASE civmodcore;
CREATE DATABASE castlegates;
CREATE DATABASE essenceglue;
CREATE DATABASE exilepearl;
CREATE DATABASE realisticbiomes;
CREATE DATABASE heliodor;

GRANT ALL PRIVILEGES ON `donum`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `banstick`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `bastion`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `citadel`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civchat2`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civduties`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `jukealert`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `namelayer`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civmodcore`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `castlegates`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `essenceglue`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `exilepearl`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `realisticbiomes`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `heliodor`.* TO 'mariadb'@'%';

CREATE DATABASE pvp_civduties;
CREATE DATABASE pvp_civmodcore;
CREATE DATABASE pvp_kitpvp;

GRANT ALL PRIVILEGES ON `pvp_civduties`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `pvp_civmodcore`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `pvp_kitpvp`.* TO 'mariadb'@'%';

CREATE DATABASE gamma_civduties;
CREATE DATABASE gamma_civmodcore;
CREATE DATABASE gamma_bastion;
CREATE DATABASE gamma_castlegates;
CREATE DATABASE gamma_citadel;
CREATE DATABASE gamma_civchat2;
CREATE DATABASE gamma_donum;
CREATE DATABASE gamma_essenceglue;
CREATE DATABASE gamma_jukealert;
CREATE DATABASE gamma_namelayer;
CREATE DATABASE gamma_exilepearl;
CREATE DATABASE gamma_heliodor;
CREATE DATABASE gamma_realisticbiomes;

GRANT ALL PRIVILEGES ON `gamma_civduties`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_civmodcore`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_bastion`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_castlegates`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_citadel`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_civchat2`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_donum`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_essenceglue`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_jukealert`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_heliodor`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_realisticbiomes`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_namelayer`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `gamma_exilepearl`.* TO 'mariadb'@'%';
