- name: Maven | Create folder
  when:
    - "'swarm_manager' in group_names"
    - setting.maven.enabled
  file:
    path: /opt/stacks/maven
    state: directory

- name: Maven | Create volume folders
  when:
    - "'swarm_manager' in group_names"
    - setting.maven.enabled
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /opt/stacks/maven/nexus-data

- name: Maven | Copy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.maven.enabled
  template:
    src: ../../templates/stacks/maven.yml
    dest: /opt/stacks/maven/maven.yml

- name: Maven | Deploy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.maven.enabled
  docker_stack:
    state: present
    name: maven
    compose:
      - /opt/stacks/maven/maven.yml
