- name: Minecraft | Create Folder
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  file:
    path: /opt/stacks/minecraft
    state: directory

- name: Minecraft | Create volume folders
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /opt/stacks/minecraft/paper-data
    - /opt/stacks/minecraft/mariadb-data
    - /opt/stacks/minecraft/postgres-data

- name: Minecraft | Copy Templates
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  template:
    src: ../../templates/stacks/minecraft.yml.j2
    dest: /opt/stacks/minecraft/minecraft.yml

# TODO: ansible.posix.synchronize delegates to rsync and can't use the sudo password, so for now we do this nonsense.
# This is a little slow, but I've futzed around for a while and need to get this just working so we can keep developing.

- name: Minecraft | Remove Files
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  file:
    path: '{{item}}'
    state: absent
  loop:
    - /opt/stacks/minecraft/paper-config
    - /opt/stacks/minecraft/paper-plugins

- name: Minecraft | Copy Files
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  copy:
    src: '../../templates/stacks/minecraft/{{item}}'
    dest: '/opt/stacks/minecraft'
  loop:
    - paper-config
    - paper-plugins

- name: Minecraft | Deploy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  docker_stack:
    state: present
    name: minecraft
    compose:
      - /opt/stacks/minecraft/minecraft.yml
