- name: Monitoring | Create folder
  when:
    - "'swarm_manager' in group_names"
    - setting.monitoring.enabled
  file:
    path: /opt/stacks/monitoring
    state: directory

- name: Monitoring | Create volume folders
  when:
    - "'swarm_manager' in group_names"
    - setting.monitoring.enabled
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /opt/stacks/monitoring/grafana-data
    - /opt/stacks/monitoring/loki-data

- name: Monitoring | Copy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.monitoring.enabled
  template:
    src: ../../templates/stacks/monitoring.yml
    dest: /opt/stacks/monitoring/monitoring.yml

- name: Monitoring | Deploy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.monitoring.enabled
  docker_stack:
    state: present
    name: monitoring
    compose:
      - /opt/stacks/monitoring/monitoring.yml