- name: Portainer | Create folder
  when:
    - "'swarm_manager' in group_names"
    - setting.portainer.enabled
  file:
    path: /opt/stacks/portainer
    state: directory

- name: Portainer | Create volume folders
  when:
    - "'swarm_manager' in group_names"
    - setting.portainer.enabled
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /opt/stacks/portainer/portainer-data

- name: Portainer | Copy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.portainer.enabled
  template:
    src: ../../templates/stacks/portainer.yml
    dest: /opt/stacks/portainer/portainer.yml

- name: Portainer | Deploy Stack
  when:
    - "'swarm_manager' in group_names"
    - setting.portainer.enabled
  docker_stack:
    state: present
    name: portainer
    compose:
      - /opt/stacks/portainer/portainer.yml