package net.civmc.namelayer.sync;

public enum NameLayerWriteOperation {
    ADD_BLACKLIST,
    ADD_INVITATION,
    ADD_MEMBER,
    ADD_PERMISSION,
    ACCEPT_INVITATION,
    CREATE_GROUP,
    DELETE_GROUP,
    ENSURE_NEWFRIEND_GROUP,
    JOIN_GROUP,
    LEAVE_GROUP,
    REMOVE_BLACKLIST,
    REMOVE_INVITATION,
    REMOVE_MEMBER,
    REMOVE_PERMISSION,
    RENAME_GROUP,
    SET_AUTO_ACCEPT,
    SET_DEFAULT_GROUP,
    SET_GROUP_COLOR,
    SET_GROUP_DISCIPLINE,
    SET_GROUP_OWNER,
    SET_GROUP_PASSWORD,
    SET_MEMBER_ROLE
}
