package net.civmc.namelayer.sync;

public enum NameLayerWriteFailureCode {
    AUTHORIZATION_FAILED,
    DATABASE_UNAVAILABLE,
    GROUP_NOT_FOUND,
    INVALID_REQUEST,
    MAX_GROUPS_REACHED,
    MEMBER_NOT_FOUND,
    NAME_CONFLICT,
    PLAYER_NOT_FOUND,
    UNKNOWN_OPERATION,
    WRITE_FAILED
}
