name: Build

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Waterfall Docker image
        uses: docker/build-push-action@v2
        with:
          context: waterfall
          tags: ghcr.io/civmc/civdocker/waterfall:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push Paper Docker image
        uses: docker/build-push-action@v2
        with:
          context: paper
          tags: ghcr.io/civmc/civdocker/paper:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}



