name: 'Update Plugin'

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: The plugin from this organization to update
        required: true
        type: string
env:
    GH_TOKEN: ${{ github.token }}

jobs:
  update_plugin:
    runs-on: ubuntu-latest

    steps:
      - name: List Releases
        run: gh release list -R ${{ github.repository_owner }}/${{ inputs.plugin }}