- name: Configure Backups | Create folder
  when:
    - "'swarm_manager' in group_names"
  file:
    path: /opt/backups
    state: directory

- name: Configure Backups | Copy Script
  when: "'swarm_manager' in group_names"
  template:
    src: ../../templates/backup-and-restart.sh
    dest: /opt/backup-and-restart.sh
