version: '3.8'

services:

  waterfall:
    build: waterfall
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"

  paper:
    build: paper
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 5G

      CIV_MYSQL_HOST: mariadb
      CIV_MYSQL_USERNAME: username
      CIV_MYSQL_PASSWORD: password
      CIV_MYSQL_DATABASE: minecraft
    volumes:
      - ./local/paper:/data

  mariadb:
    image: mariadb:10.7.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: minecraft
    volumes:
      - ./local/mariadb:/var/lib/mysql
