version: '3.9'

services:

  waterfall:
    build: waterfall
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - mariadb
      - influx
    ports:
      - "25565:25577"

  paper:
    build: paper
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      mariadb:
        condition: service_healthy
      influx:
        condition: service_started
    ports:
      - "8123:8123"
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 5G

      CIV_SERVER_NAME: local

      CIV_MYSQL_HOST: mariadb
      CIV_MYSQL_USERNAME: username
      CIV_MYSQL_PASSWORD: password
      CIV_MYSQL_DATABASE: minecraft

      CIV_INFLUX_HOST: http://influx:8086
      CIV_INFLUX_ORG: CivMC
      CIV_INFLUX_BUCKET: UnifiedMetrics
      CIV_INFLUX_TOKEN: admintoken
    volumes:
      - ./local/paper:/data

  mariadb:
    image: mariadb:10.7.1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: minecraft
    volumes:
      - ./local/mariadb:/var/lib/mysql


  influx:
    image: influxdb:2.1-alpine
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: username
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: CivMC
      DOCKER_INFLUXDB_INIT_BUCKET: UnifiedMetrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admintoken
    volumes:
      - ./local/influx:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    depends_on:
      - influx
    profiles:
      - extra
    ports:
      - "3000:3000"
    environment:
      CIV_INFLUX_HOST: http://influx:8086
      CIV_INFLUX_ORG: CivMC
      CIV_INFLUX_TOKEN: admintoken
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

