name: Ping
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Ping'
        type: environment
        required: true 
        default: Test

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inject secrets
        run: 'echo "$SECRETS_YML" > variables/secrets.yml'
        shell: bash
        env:
          SECRETS_YML: ${{secrets.SECRETS_YML}}

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p /home/runner/.ssh
          echo -e "${{secrets.SSH_PRIVATE_KEY}}" >> /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_KNOWN_HOSTS}}" >> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/known_hosts

      - name: Ping
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/ping.yml
          requirements: requirements.yml
          options: |
            --inventory ./inventories/civmc-${{inputs.environment}}.yml

