name: Setup Server
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Setup'
        type: environment
        required: true 
        default: Test

jobs:
  setup-server:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inject secrets
        run: 'echo "$SECRETS_YML" > variables/secrets.yml'
        shell: bash
        env:
          SECRETS_YML: ${{secrets.SECRETS_YML}}
          SUDO_PASSWORD: ${{secrets.SUDO_PASSWORD}}

      - name: Setup Server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/setup-server.yml
          requirements: requirements.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          options: |
            --inventory ./inventories/civmc-${{inputs.environment}}.yml
            -e "ansible_become_password=${{secrets.SUDO_PASSWORD}}"
