version: '3.8'

services:

  keycloak:
    image: jboss/keycloak:latest
    restart: always
    networks:
      - auth_default
      - traefik-public
    environment:
      KEYCLOAK_USER: '{{secret.auth.keycloak.user}}'
      KEYCLOAK_PASSWORD: '{{secret.auth.keycloak.password}}'
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: '{{secret.auth.postgres.password}}'
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.keycloak-public-http.rule=Host(`{{secret.auth.keycloak.host}}`)
        - traefik.http.routers.keycloak-public-http.entrypoints=http
        - traefik.http.routers.keycloak-public-http.middlewares=https-redirect
        - traefik.http.routers.keycloak-public-https.rule=Host(`{{secret.auth.keycloak.host}}`)
        - traefik.http.routers.keycloak-public-https.entrypoints=https
        - traefik.http.routers.keycloak-public-https.tls=true
        - traefik.http.routers.keycloak-public-https.tls.certresolver=le
        - traefik.http.services.keycloak-public.loadbalancer.server.port=8080
    logging:
        driver: grafana/loki-docker-driver
        options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-retries: "5"
          loki-batch-size: "400"

  postgres:
    image: postgres:14
    restart: always
    networks:
      - auth_default
    volumes:
      - /opt/stacks/auth/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: '{{secret.auth.postgres.password}}'
      POSTGRES_DB: keycloak
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "$keycloak" ]
      timeout: 45s
      interval: 10s
      retries: 10
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
        driver: grafana/loki-docker-driver
        options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-retries: "5"
          loki-batch-size: "400"

networks:
  auth_default:
  traefik-public:
    external: true
