settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  axolotls: 1
  monsters: 6
  animals: 1
  water-animals: 1
  water-ambient: 1
  water-underground-creature: 1
  ambient: 1
chunk-gc:
  period-in-ticks: 400
ticks-per:
  axolotl-spawns: 4800
  animal-spawns: 4800
  monster-spawns: 400
  water-spawns: 7200
  water-ambient-spawns: 7200
  water-underground-creature-spawns: 7200
  ambient-spawns: 7200
  autosave: 6000
aliases: now-in-commands.yml
worlds:
  world:
    generator: ${CIV_WORLD_GENERATOR}
