settings:
  default: &default
    # Default Stacks
    traefik:
      enabled: true
    monitoring:
      enabled: true
    minecraft: &default_minecraft
      enabled: true
      whitelist: false
      pvp_whitelist: false
      gamma_whitelist: false
      pvp_hostname: 'pvp.civmc.net'
      hostname: 'play.civmc.net'
      gamma_hostname: 'mini.civmc.net'
      resources: &default_minecraft_resources
        memory: 44G
        memory_limit: 48G
        pvp_memory: 11G
        pvp_memory_limit: 14G
        gamma_memory: 21G
        gamma_memory_limit: 24G
    # Optional Stacks
    auth:
      enabled: false
    maven:
      enabled: false

  production:
    <<: *default
    environment: Production
    minecraft:
      <<: *default_minecraft
    auth:
      enabled: false # TODO: MOVE

  test:
    <<: *default
    environment: Test
    minecraft:
      <<: *default_minecraft
      whitelist: true
      pvp_whitelist: true
      gamma_whitelist: true
      gamma_hostname: 'mini-test.civmc.net'
      pvp_hostname: 'pvp-test.civmc.net'
      hostname: 'test.civmc.net'
      resources:
        <<: *default_minecraft_resources
        memory: 4G
        memory_limit: 6G
        pvp_memory: 3G
        pvp_memory_limit: 5G
        gamma_memory: 4G
        gamma_memory_limit: 6G
    auth:
      enabled: true # TODO: MOVE
    maven:
      enabled: true # TODO: MOVE
