settings:
  default: &default
    # Default Stacks
    traefik:
      enabled: true
    monitoring:
      enabled: true
    minecraft: &default_minecraft
      enabled: true
      whitelist: false
      resources: &default_minecraft_resources
        memory: 40G
        pvp_memory: 10G
    # Optional Stacks
    auth:
      enabled: false
    maven:
      enabled: false

  production:
    <<: *default
    environment: Production
    minecraft:
      <<: *default_minecraft
      pvp_hostname: 'pvp.civmc.net'
    auth:
      enabled: false # TODO: MOVE

  test:
    <<: *default
    environment: Test
    minecraft:
      <<: *default_minecraft
      whitelist: true
      pvp_hostname: 'pvp-test.civmc.net'
      resources:
        <<: *default_minecraft_resources
        memory: 6G
        pvp_memory: 7G
    auth:
      enabled: true # TODO: MOVE
    maven:
      enabled: true # TODO: MOVE
