settings:
  default: &default
    # Default Stacks
    traefik:
      enabled: true
    monitoring:
      enabled: true
    minecraft:
      enabled: true
    # Optional Stacks
    auth:
      enabled: false

  production:
    <<: *default
    auth:
      enabled: false # TODO: MOVE

  test:
    <<: *default
    auth:
      enabled: true # TODO: MOVE
