/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.3.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://raw.githubusercontent.com/CivClassic/artifacts/master/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://libraries.minecraft.net")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

tasks {
  build {
    dependsOn(reobfJar)
  }

  compileJava {
      options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything

      // Set the release flag. This configures what version bytecode the compiler will emit, as well as what JDK APIs are usable.
      // See https://openjdk.java.net/jeps/247 for more information.
      options.release.set(17)
    }
    javadoc {
      options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything
    }
    processResources {
      filteringCharset = Charsets.UTF_8.name() // We want UTF-8 for everything
    }
}


java {
  toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

dependencies {
    paperDevBundle("1.18-R0.1-SNAPSHOT")
    implementation("com.mojang:datafixerupper:1.0.20")
    implementation("com.zaxxer:HikariCP:3.4.2")
    implementation("net.kyori:adventure-text-minimessage:4.1.0-SNAPSHOT")
    implementation("co.aikar:acf-bukkit:0.5.0-SNAPSHOT")
    implementation("co.aikar:taskchain-bukkit:3.7.2")
    implementation("com.github.IPVP-MC:canvas:91ec97f076")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("it.unimi.dsi:fastutil:8.2.2")
    implementation("co.aikar:cleaner:1.0-SNAPSHOT")
    testImplementation("junit:junit:4.13.2")
    compileOnly("org.projectlombok:lombok:1.18.20")
    annotationProcessor ("org.projectlombok:lombok:1.18.20")
}

group = "com.github.civclassic"
version = "2.0.0"
description = "CivModCore"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}


