/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.3.1"
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

group = "net.civmc"
version = "2.0.0-SNAPSHOT"
description = "CivModCore"

repositories {
	mavenCentral()
	maven("https://repo.aikar.co/content/groups/aikar/")
    maven("https://jitpack.io")
    maven("https://libraries.minecraft.net")
}

dependencies {
	paperDevBundle("1.18-R0.1-SNAPSHOT")

    implementation("com.mojang:datafixerupper:1.0.20")
    implementation("com.zaxxer:HikariCP:3.4.2")
    implementation("net.kyori:adventure-text-minimessage:4.1.0-SNAPSHOT")
    implementation("co.aikar:acf-bukkit:0.5.0-SNAPSHOT")
    implementation("co.aikar:taskchain-bukkit:3.7.2")
    implementation("com.github.IPVP-MC:canvas:91ec97f076")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("it.unimi.dsi:fastutil:8.2.2")
    implementation("co.aikar:cleaner:1.0-SNAPSHOT")

     compileOnly("org.projectlombok:lombok:1.18.20")
     annotationProcessor ("org.projectlombok:lombok:1.18.20")

	testImplementation("org.junit.jupiter:junit-jupiter-api:5.2.0")
	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.2.0")
}

java {
	toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

tasks {
	build {
		dependsOn(reobfJar)
	}

	compileJava {
		options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything

		// Set the release flag. This configures what version bytecode the compiler will emit, as well as what JDK APIs are usable.
		// See https://openjdk.java.net/jeps/247 for more information.
		options.release.set(17)
	}
	javadoc {
		options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything
	}
	processResources {
		filteringCharset = Charsets.UTF_8.name() // We want UTF-8 for everything
	}

	test {
		useJUnitPlatform()
	}

	shadowJar {
		// helper function to relocate a package into our package
		fun reloc(pkg: String) = relocate(pkg, "vg.civcraft.mc.civmodcore.dependencies.$pkg")

		// relocate and it's transitive dependencies
		reloc("com.mojang")
		reloc("com.zaxxer")
		reloc("net.kyori")
		reloc("org.apache")
		reloc("com.google")
	}
}

publishing {
	repositories {
		maven {
			name = "GitHubPackages"
			url = uri("https://maven.pkg.github.com/CivModCore")
			credentials {
				username = System.getenv("GITHUB_ACTOR")
				password = System.getenv("GITHUB_TOKEN")
			}
		}
	}
	publications {
		register<MavenPublication>("gpr") {
			from(components["java"])
		}
	}
}
