- name: Deploy
  hosts: all
  become: true

  tasks:
    - name: Deploy | Expand setting
      include: ../tasks/expand-setting.yml

    - name: Deploy | Include Tasks
      include_tasks:
        file: '../tasks/deploy/{{deploy_task}}.yml'
      loop:
        - portainer
        - auth
        - traefik
        - minecraft
        - monitoring
      loop_control:
        loop_var: deploy_task
