- name: Start Server
  hosts: all
  become: true

  tasks:
    - name: Start Server | Expand setting
      include: ../tasks/expand-setting.yml

    - name: Start Server | Include Start Tasks
      include_tasks:
        file: '../tasks/start-server.yml'
