# TODO: Use docker module, currently it doesn't seem to support updating.
- name: Stop Server | Stop Waterfall
  when:
    - "'swarm_manager' in group_names"
    - - "'proxy' in servers"
    - setting.minecraft.enabled
  command: docker service scale minecraft_waterfall=0

- name: Stop Server | Stop Paper
  when:
    - "'swarm_manager' in group_names"
    - "'paper' in servers"
    - setting.minecraft.enabled
  command: docker service scale minecraft_paper=0

- name: Stop Server | Stop PvP
  when:
    - "'swarm_manager' in group_names"
    - "'pvp' in servers"
    - setting.minecraft.enabled
  command: docker service scale minecraft_pvp=0
