- name: Stop Server | Stop Server
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  community.docker.docker_stack_info:
  register: result

- name: Show results
  ansible.builtin.debug:
    var: result.results
