# TODO: Use docker module, currently it doesn't seem to support updating.
- name: Stop Server | Stop Waterfall
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  command: docker service scale minecraft_waterfall=0

- name: Stop Server | Stop Paper
  when:
    - "'swarm_manager' in group_names"
    - setting.minecraft.enabled
  command: docker service scale minecraft_paper=0
