/**
 * @author Aleksey Terzi
 *
 */

package com.aleksey.castlegates.config;

import org.bukkit.Material;

public class ConfigDefaults {
	public static final String[] gearMaterials = new String[] {
		Material.STONE.name(),
		Material.GRASS.name(),
		Material.DIRT.name(),
		Material.COBBLESTONE.name(),

		Material.OAK_WOOD.name(),
		Material.OAK_LOG.name(),
		Material.OAK_PLANKS.name(),
		Material.OAK_STAIRS.name(),
		Material.OAK_FENCE.name(),
		Material.OAK_SLAB.name(),
		Material.STRIPPED_OAK_LOG.name(),
		Material.STRIPPED_OAK_WOOD.name(),

		Material.SPRUCE_WOOD.name(),
		Material.SPRUCE_LOG.name(),
		Material.SPRUCE_PLANKS.name(),
		Material.SPRUCE_STAIRS.name(),
		Material.SPRUCE_FENCE.name(),
		Material.SPRUCE_SLAB.name(),
		Material.STRIPPED_SPRUCE_LOG.name(),
		Material.STRIPPED_SPRUCE_WOOD.name(),

		Material.BIRCH_WOOD.name(),
		Material.BIRCH_LOG.name(),
		Material.BIRCH_PLANKS.name(),
		Material.BIRCH_STAIRS.name(),
		Material.BIRCH_FENCE.name(),
		Material.BIRCH_SLAB.name(),
		Material.STRIPPED_BIRCH_LOG.name(),
		Material.STRIPPED_BIRCH_WOOD.name(),

		Material.JUNGLE_WOOD.name(),
		Material.JUNGLE_LOG.name(),
		Material.JUNGLE_PLANKS.name(),
		Material.JUNGLE_STAIRS.name(),
		Material.JUNGLE_FENCE.name(),
		Material.JUNGLE_SLAB.name(),
		Material.STRIPPED_JUNGLE_LOG.name(),
		Material.STRIPPED_JUNGLE_WOOD.name(),

		Material.ACACIA_WOOD.name(),
		Material.ACACIA_LOG.name(),
		Material.ACACIA_PLANKS.name(),
		Material.ACACIA_STAIRS.name(),
		Material.ACACIA_FENCE.name(),
		Material.ACACIA_SLAB.name(),
		Material.STRIPPED_ACACIA_LOG.name(),
		Material.STRIPPED_ACACIA_WOOD.name(),

		Material.DARK_OAK_WOOD.name(),
		Material.DARK_OAK_LOG.name(),
		Material.DARK_OAK_PLANKS.name(),
		Material.DARK_OAK_STAIRS.name(),
		Material.DARK_OAK_FENCE.name(),
		Material.DARK_OAK_SLAB.name(),
		Material.STRIPPED_DARK_OAK_LOG.name(),
		Material.STRIPPED_DARK_OAK_WOOD.name(),

		Material.GLASS.name(),
		Material.LAPIS_BLOCK.name(),
		Material.SANDSTONE.name(),

		Material.WHITE_WOOL.name(),
		Material.ORANGE_WOOL.name(),
		Material.MAGENTA_WOOL.name(),
		Material.LIGHT_BLUE_WOOL.name(),
		Material.YELLOW_WOOL.name(),
		Material.LIME_WOOL.name(),
		Material.PINK_WOOL.name(),
		Material.GRAY_WOOL.name(),
		Material.LIGHT_GRAY_WOOL.name(),
		Material.CYAN_WOOL.name(),
		Material.PURPLE_WOOL.name(),
		Material.BLUE_WOOL.name(),
		Material.BROWN_WOOL.name(),
		Material.GREEN_WOOL.name(),
		Material.RED_WOOL.name(),
		Material.BLACK_WOOL.name(),

		Material.GOLD_BLOCK.name(),
		Material.IRON_BLOCK.name(),
		Material.BRICK.name(),
		Material.MOSSY_COBBLESTONE.name(),
		Material.MOSSY_COBBLESTONE_SLAB.name(),
		Material.OBSIDIAN.name(),
		Material.DIAMOND_BLOCK.name(),
		Material.COBBLESTONE_STAIRS.name(),
		Material.COBBLESTONE_SLAB.name(),
		Material.ICE.name(),
		Material.SNOW_BLOCK.name(),
		Material.CLAY.name(),
		Material.NETHERRACK.name(),
		Material.GLOWSTONE.name(),
		Material.SMOOTH_STONE.name(),
		Material.IRON_BARS.name(),
		Material.BRICK_STAIRS.name(),
		Material.NETHER_BRICK.name(),
		Material.NETHER_BRICK_STAIRS.name(),
		Material.SANDSTONE_STAIRS.name(),
		Material.EMERALD_BLOCK.name(),
		Material.REDSTONE_BLOCK.name(),
		Material.QUARTZ_BLOCK.name(),
		Material.QUARTZ_STAIRS.name(),
		Material.ACACIA_STAIRS.name(),
		Material.DARK_OAK_STAIRS.name(),
		Material.HAY_BLOCK.name(),
		Material.COAL_BLOCK.name(),
		Material.PACKED_ICE.name(),
		Material.RED_SANDSTONE.name(),
		Material.RED_SANDSTONE_STAIRS.name(),
		Material.SPRUCE_FENCE.name(),
		Material.BIRCH_FENCE.name(),
		Material.JUNGLE_FENCE.name(),
		Material.DARK_OAK_FENCE.name(),
		Material.ACACIA_FENCE.name(),
		Material.PURPUR_BLOCK.name(),
		Material.PURPUR_STAIRS.name(),
		Material.PURPUR_SLAB.name(),
		Material.MAGMA_BLOCK.name(),
		Material.NETHER_WART_BLOCK.name(),
		Material.RED_NETHER_BRICKS.name(),
		Material.BONE_BLOCK.name()
	};

	public static final String[] bridgeMaterials = new String[] {
		Material.STONE.name(),
		Material.DIRT.name(),
		Material.COBBLESTONE.name(),

		Material.OAK_WOOD.name(),
		Material.OAK_LOG.name(),
		Material.OAK_PLANKS.name(),
		Material.OAK_FENCE.name(),
		Material.STRIPPED_OAK_LOG.name(),
		Material.STRIPPED_OAK_WOOD.name(),

		Material.SPRUCE_WOOD.name(),
		Material.SPRUCE_LOG.name(),
		Material.SPRUCE_PLANKS.name(),
		Material.SPRUCE_FENCE.name(),
		Material.STRIPPED_SPRUCE_LOG.name(),
		Material.STRIPPED_SPRUCE_WOOD.name(),

		Material.BIRCH_WOOD.name(),
		Material.BIRCH_LOG.name(),
		Material.BIRCH_PLANKS.name(),
		Material.BIRCH_FENCE.name(),
		Material.STRIPPED_BIRCH_LOG.name(),
		Material.STRIPPED_BIRCH_WOOD.name(),

		Material.JUNGLE_WOOD.name(),
		Material.JUNGLE_LOG.name(),
		Material.JUNGLE_PLANKS.name(),
		Material.JUNGLE_FENCE.name(),
		Material.STRIPPED_JUNGLE_LOG.name(),
		Material.STRIPPED_JUNGLE_WOOD.name(),

		Material.ACACIA_WOOD.name(),
		Material.ACACIA_LOG.name(),
		Material.ACACIA_PLANKS.name(),
		Material.ACACIA_FENCE.name(),
		Material.STRIPPED_ACACIA_LOG.name(),
		Material.STRIPPED_ACACIA_WOOD.name(),

		Material.DARK_OAK_WOOD.name(),
		Material.DARK_OAK_LOG.name(),
		Material.DARK_OAK_PLANKS.name(),
		Material.DARK_OAK_FENCE.name(),
		Material.STRIPPED_DARK_OAK_LOG.name(),
		Material.STRIPPED_DARK_OAK_WOOD.name(),

		Material.GLASS.name(),
		Material.LAPIS_BLOCK.name(),
		Material.SANDSTONE.name(),

		Material.WHITE_WOOL.name(),
		Material.ORANGE_WOOL.name(),
		Material.MAGENTA_WOOL.name(),
		Material.LIGHT_BLUE_WOOL.name(),
		Material.YELLOW_WOOL.name(),
		Material.LIME_WOOL.name(),
		Material.PINK_WOOL.name(),
		Material.GRAY_WOOL.name(),
		Material.LIGHT_GRAY_WOOL.name(),
		Material.CYAN_WOOL.name(),
		Material.PURPLE_WOOL.name(),
		Material.BLUE_WOOL.name(),
		Material.BROWN_WOOL.name(),
		Material.GREEN_WOOL.name(),
		Material.RED_WOOL.name(),
		Material.BLACK_WOOL.name(),

		Material.GOLD_BLOCK.name(),
		Material.IRON_BLOCK.name(),
		Material.BRICK.name(),
		Material.MOSSY_COBBLESTONE.name(),
		Material.DIAMOND_BLOCK.name(),
		Material.COBBLESTONE_STAIRS.name(),
		Material.ICE.name(),
		Material.SNOW_BLOCK.name(),
		Material.CLAY.name(),
		Material.NETHERRACK.name(),
		Material.GLOWSTONE.name(),
		Material.BRICK_STAIRS.name(),
		Material.NETHER_BRICK.name(),
		Material.NETHER_BRICK_STAIRS.name(),
		Material.SANDSTONE_STAIRS.name(),
		Material.EMERALD_BLOCK.name(),
		Material.REDSTONE_BLOCK.name(),
		Material.QUARTZ_BLOCK.name(),
		Material.QUARTZ_STAIRS.name(),
		Material.ACACIA_STAIRS.name(),
		Material.DARK_OAK_STAIRS.name(),
		Material.HAY_BLOCK.name(),
		Material.COAL_BLOCK.name(),
		Material.PACKED_ICE.name(),
		Material.RED_SANDSTONE.name(),
		Material.RED_SANDSTONE_STAIRS.name(),
		Material.SPRUCE_FENCE.name(),
		Material.BIRCH_FENCE.name(),
		Material.JUNGLE_FENCE.name(),
		Material.DARK_OAK_FENCE.name(),
		Material.ACACIA_FENCE.name(),
		Material.PURPUR_BLOCK.name(),
		Material.PURPUR_STAIRS.name(),
		Material.PURPUR_SLAB.name(),
	};
}
