/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.3.1"
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

group = "net.civmc"
version = "4.3.0"
description = "Citadel"

repositories {
    mavenCentral()
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://papermc.io/repo/repository/maven-public/")
    maven("https://maven.pkg.github.com/CivMC/CivModCore")
    maven("https://repo.maven.apache.org/maven2/")
}

dependencies {
	paperDevBundle("1.18-R0.1-SNAPSHOT")
	implementation("net.civmc:civmodcore:2.0.0-SNAPSHOT")
	implementation("net.civmc:NameLayer:2.16.0")
	implementation("com.gmail.filoghost.holographicdisplays:holographicdisplays-api:2.4.8")
}

java {
	toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

tasks {
	build {
		dependsOn(reobfJar)
	}

	compileJava {
		options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything

		// Set the release flag. This configures what version bytecode the compiler will emit, as well as what JDK APIs are usable.
		// See https://openjdk.java.net/jeps/247 for more information.
		options.release.set(17)
	}
	javadoc {
		options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything
	}
	processResources {
		filteringCharset = Charsets.UTF_8.name() // We want UTF-8 for everything
	}

	test {
		useJUnitPlatform()
	}

	shadowJar {
		// helper function to relocate a package into our package
		fun reloc(pkg: String) = relocate(pkg, "vg.civcraft.mc.citadel.dependencies.$pkg")

		// relocate and it's transitive dependencies
		//reloc("com.mojang")
	}
}

publishing {
	repositories {
		maven {
			name = "GitHubPackages"
			url = uri("https://maven.pkg.github.com/CivMC/Citadel")
			credentials {
				username = System.getenv("GITHUB_ACTOR")
				password = System.getenv("GITHUB_TOKEN")
			}
		}
	}
	publications {
		register<MavenPublication>("gpr") {
			from(components["java"])
		}
	}
}
