server_connect_timeout: 10000
listeners:
  - query_port: 25565
    motd: "§rYou're a §l§abeautiful§r person."
    tab_list: GLOBAL
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: true
    host: "0.0.0.0:25577"
    max_players: 420
    tab_size: 60
    force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: 420
ip_forward: true
groups:
  md_5:
    - adminnnn
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: b074eed2-e7a2-4cda-bc1c-badda2fb5223
online_mode: true
forge_support: true
disabled_commands:
  - disabledcommandhere
servers:
  lobby:
    motd: '&1CivMC'
    address: "paper:25566"
    restricted: false
