/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "simpleadminhacks"

pluginManagement {
  repositories {
    gradlePluginPortal()
    maven("https://papermc.io/repo/repository/maven-public/")
  }
}
