# Build a project
name: 🐘 Gradle | Build Project

on:
  workflow_dispatch:
    inputs:
      category:
        required: true
        description: 'The category of project'
        type: choice
        options:
          - plugins
      project:
        required: true
        description: 'The project to build'
        type: string
  workflow_call:
    inputs:
      category:
        required: true
        description: 'The category of project'
        type: string
      project:
        required: true
        description: 'The project to build'
        type: string

jobs:
  build_gradle:
    name: 🐘 Build Gradle
    runs-on: ubuntu-22.04

    steps:
      - name: 🚩 Checkout Repo
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 🐘 Gradle Build
        run: CI=true ./gradlew ${{inputs.category}}:${{inputs.project}}:build --scan

      - name: 🗃️ Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: '**/build/libs/*'
