# Lint all YAML
name: 🔎 Lint Yaml

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint_yaml:
    name: 🔎 Lint Yaml
    runs-on: ubuntu-24.04

    steps:
      - name: 🚩 Checkout Repo
        uses: actions/checkout@v4

      - name: 🔎 Lint Yaml
        uses: ibiqlik/action-yamllint@v3
        continue-on-error: true # TODO: Remove after checks pass
