name: ✅ PR Updated Completed

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "⬇️ PR Updated"

jobs:
  call_comment_on_pr:
    name: ☎️ Call  Comment on PR
    uses: ./.github/workflows/check_gradle_all.yaml
    secrets: inherit
